<style>
  root {
    FontName Padauk;
    BackgroundColor #FAFAFA;
  }
  component {
    BackgroundColor #31176B;
    b1a8d4
    BorderColor #64B5F6;
    FontColor #FAFAFA;
    FontSize 14;
    RoundCorner 10;
    Padding 8;
    Shadowing 2;
  }

  node {
    BackgroundColor #FAFAFA;
    BorderColor #78909C;
    FontSize 14;
    RoundCorner 8;
    Padding 10;
    Shadowing 3;
  }

  database {
    BackgroundColor #888;
    BorderColor #66BB6A;
    FontColor #FAFAFA;
    FontSize 14;
    RoundCorner 8;
    Shadowing 2;
  }

  actor {
    BackgroundColor #CB159A;
    BorderColor #FF9800;
    FontColor #CB159A;
    FontSize 14;
    RoundCorner 8;
    Padding 6;
  }

  queue {
    BackgroundColor #F2C633;
    FontColor #121212;
  }

  arrow {
    LineColor #444;
    LineThickness 2;
  }

  note {
    BackgroundColor #CB159A;
    BorderColor #FDD835;
    FontColor #FAFAFA;
  }

  cloud {
    LineColor #31176B;
  }

  frame {
    LineColor #31176B;
  }

  folder {
    LineColor #F2C633;
  }
</style>

!define to [thickness=3]
!define err [#red]
!define db [#gray]
!define errLabel(x) <color:red><b>x</b></color>
!define dbLabel(x) <color:gray><b>x</b></color>
