@startuml
!define COLOR_MAIN #005F7F
!define COLOR_ALT #00BAC6
!define COLOR_ACCENT #CBDB2A
!define COLOR_ERROR #6E1100
!define COLOR_SUCCESS #009532
!define COLOR_GRAY #585858

!define PATH_MAIN thickness=3
!define PATH_COMMON thickness=1

!define errorLabel(x) <color:#CB2000><b>x</b></color>
!define successLabel(x) <color:#009532><b>x</b></color>
!define dbLabel(x) <color:#585858><b>x</b></color>

<style>

  root {
    FontName Padauk;
    BackgroundColor #FAFAFA;
  }
  component {
    BackgroundColor #005F7F;
    b1a8d4
    BorderColor #64B5F6;
    FontColor #FAFAFA;
    FontSize 14;
    RoundCorner 10;
    Padding 8;
    Shadowing 2;
  }

  node {
    BackgroundColor #FAFAFA;
    BorderColor #78909C;
    FontSize 14;
    RoundCorner 8;
    Padding 10;
    Shadowing 3;
  }

  database {
    BackgroundColor #888;
    BorderColor #66BB6A;
    FontColor #FAFAFA;
    FontSize 14;
    RoundCorner 8;
    Shadowing 2;
  }

  actor {
    BackgroundColor #CBDB2A;
    BorderColor #FF9800;
    FontColor #585858;
    FontSize 14;
    RoundCorner 8;
    Padding 6;
  }

  queue {
    BackgroundColor #CBDB2A;
    FontColor #121212;
  }

  arrow {
    LineColor #444;
    LineThickness 2;
  }

  note {
    BackgroundColor #585858;
    BorderColor #121212;
    FontColor #FAFAFA;
  }

  cloud {
    LineColor #00BAC6;
  }

  frame {
    LineColor #005F7F;
  }

  folder {
    LineColor #00BAC6;
  }
</style>
